import { SubCategory } from "../types/subcategory-types";

export const EMAIL_SUBCATEGORIES: SubCategory[] = [
  {
    id: "business",
    name: "Business Communication",
    description: "Professional business emails",
    defaultPrompt: "Write a professional email for [purpose: proposal/update/request/introduction] that [objective]. Structure with: \n\n1) Subject line that clearly indicates purpose and urgency level\n\n2) Professional greeting appropriate for relationship level (new contact vs. established relationship)\n\n3) Concise context paragraph establishing relevance and background\n\n4) Clearly stated central message in the second paragraph with bullet points for multiple items or requests\n\n5) Specific details regarding [key points] with concrete dates, numbers, or deliverables where appropriate\n\n6) Clear next steps and action items with ownership and deadlines\n\n7) Professional closing that includes availability for discussion/questions and preferred contact method\n\nThe tone should be [tone: formal/business casual/collaborative] while maintaining [company]'s communication standards regarding terminology, value propositions, and messaging hierarchy. Use appropriate business terminology for [industry] while avoiding unnecessary jargon. Strike the right balance between thoroughness and respect for the recipient's time, with the entire email optimized for mobile reading (scannable, front-loaded with key information).",
  },
  {
    id: "customer",
    name: "Customer Service",
    description: "Customer support responses",
    defaultPrompt: "Compose a customer service email response addressing [issue: complaint/inquiry/technical problem/refund request]. \n\n1) Begin with a personalized acknowledgment that validates the customer's experience and demonstrates active listening\n\n2) Express genuine empathy about the specific impact of their issue without admitting fault if liability is unclear\n\n3) Provide clear, step-by-step solutions with multiple options where possible, using numbered lists for instructions and avoiding technical jargon or condescending language\n\n4) Include specific details about [specific details] to show thoroughness and prevent follow-up questions\n\n5) Proactively address potential concerns about [related issues] before they arise\n\n6) End with a clear summary of actions taken, actions required from the customer (if any), realistic timeline expectations\n\n7) Include a sincere apology focused on the experience rather than admitting fault\n\n8) Provide appropriate reassurance about service commitment\n\n9) Offer multiple follow-up channels with direct contact information\n\nThe tone should blend professionalism with warmth, avoid corporate-speak or scripted language, and maintain consistency with the brand voice of [company/brand name].",
  },
  {
    id: "marketing",
    name: "Marketing Emails",
    description: "Promotional and campaign emails",
    defaultPrompt: "Create a marketing email for [product/service] targeting [audience]. The email should include: 1) An attention-grabbing subject line (40-60 characters) with either curiosity, urgency, or direct value proposition, 2) A preheader (85-100 characters) that complements but doesn't repeat the subject line, 3) Personalized greeting beyond just name, ideally referencing behavior or preferences, 4) Opening that immediately establishes relevance to recipient's specific situation or pain point, 5) Clear, compelling value proposition about [benefits] using the PAS (Problem-Agitation-Solution) or BAB (Before-After-Bridge) framework, 6) Evidence supporting claims (specific metrics, social proof, testimonials with attribution), 7) Feature-to-benefit translations for all technical specifications, 8) Objection handling for the primary hesitation of this audience segment, 9) Risk reversal elements (guarantee, trial, etc.), 10) Primary call-to-action (repeated 2-3 times) with urgency driver, 11) Secondary CTA for prospects at different decision stages. The copy should use sensory language, action verbs, and power words while maintaining brand voice. Design for scannability with appropriate visual hierarchy and mobile optimization. Include A/B testing variables in brackets [Option A / Option B] for key elements.",
  },
  {
    id: "influencer",
    name: "Influencer Outreach",
    description: "Collaboration and partnership emails",
    defaultPrompt: "Write an outreach email to [influencer type] for [collaboration type]. Begin with a personalized introduction demonstrating specific knowledge of their recent content, audience demographics, and unique positioning (reference at least 2 specific pieces of their work). Clearly establish your credibility and relevance to their content niche without overemphasizing your brand. Present your [unique value proposition] focused primarily on audience alignment, content enhancement, and mutual benefit rather than just compensation. Be specific about collaboration expectations, including: content format requirements, creative freedom parameters, approval process, exclusivity terms if any, timeline flexibility, and performance metrics that will define success. Offer multiple collaboration options at different commitment levels, and include specific examples of successful previous collaborations with results if available. Address potential objections proactively, especially regarding brand alignment and audience authenticity. Close with a clear, specific next step request that requires minimal effort from the influencer (quick call, specific question response) rather than asking for a proposal or extensive planning. Include all necessary brand assets and reference materials as attachments/links.",
  },
  {
    id: "corporate",
    name: "Corporate Communications",
    description: "Internal and stakeholder emails",
    defaultPrompt: "Draft a corporate communication about [topic: organizational change/policy update/quarterly results/strategic initiative] for [stakeholder group: employees/investors/board members/partners]. Structure with: 1) Descriptive subject line indicating content and required action if any, 2) Executive summary paragraph providing the essential information for those who only read the beginning, 3) Context section explaining the 'why' behind the communication and connecting to broader organizational goals, 4) Detailed information about [key updates/changes] presented in a logical progression using bulleted lists for multiple items, 5) Direct addressing of potential concerns about [issues] with transparent, honest information without speculation, 6) Clear timeline with key dates and milestones highlighted, 7) Explicit statements about what will and won't change, 8) Specific next steps and expectations with accountabilities clearly assigned, 9) Resources for additional information (contact person, intranet location, upcoming meetings). Use a tone that balances appropriate corporate formality with accessibility, avoiding unnecessary jargon, euphemisms for difficult news, or excessive corporate-speak. Include both logical arguments and emotional appeals where appropriate for the content. For sensitive communications, include language vetted by legal/compliance teams [in brackets].",
  },
  {
    id: "sales",
    name: "Sales Outreach",
    description: "Sales and prospecting emails",
    defaultPrompt: "Write a sales outreach email for [target audience: job title/industry/company size] about [product/service]. Structure with: 1) Subject line focused on specific value rather than generic offerings (25-50 characters), 2) Personalized opening showing research on the recipient's company (recent news, challenge, achievement) beyond just their name, 3) Bridge connecting their specific situation to your offering without presumption, 4) Value proposition focused on [2-3 key benefits] specific to their role responsibilities and KPIs, using metrics and outcome-oriented language, 5) Brief social proof mentioning relevant customer success (same industry/size/challenge) with specific results, 6) Credibility-building differentiator from alternatives they're likely considering, 7) Low-friction call-to-action asking for a specific micro-commitment rather than a meeting, 8) Value-forward P.S. line adding either scarcity, additional benefit, or addressing common objection. Keep the entire email under 200 words with short paragraphs (3-4 lines max). Avoid generic sales language, feature lists without benefits, or presumptive language about their challenges. Balance confidence with humility, and focus on starting a conversation rather than closing a sale. Include follow-up specifics (exact day/time you'll reach out next) to reduce uncertainty.",
  },
  {
    id: "follow",
    name: "Follow-up Emails",
    description: "Post-meeting or event follow-ups",
    defaultPrompt: "Create a follow-up email regarding [topic/event: sales meeting/interview/networking event/client presentation]. Begin by referencing a specific, memorable moment or discussion point from the interaction to establish continuity and demonstrate attentiveness. Summarize key points from [previous interaction] with focus on agreed outcomes, showing you were fully engaged. Include any promised information, resources, or answers to questions raised, delivering more than expected when possible. Clarify next steps with specific responsibilities, deadlines, and formats (who does what by when and how), avoiding ambiguity that could cause delays. Address any unresolved questions or concerns that emerged during the meeting with thoughtful responses or a path to resolution. Suggest a specific next interaction with proposed date/time options if appropriate, making it easy to continue momentum. Close with forward-looking value statement connecting to broader goals beyond immediate next steps. For sales contexts, include an additional insight or value-add not mentioned in the original meeting to demonstrate ongoing value. Strike a tone that maintains the rapport level established in person while remaining professional.",
  },
  {
    id: "networking",
    name: "Professional Networking",
    description: "Network building and connections",
    defaultPrompt: "Write a networking email to [contact: new connection/existing relationship/potential mentor/industry leader] regarding [purpose: introduction/reconnection/advice request/value offer]. Begin by establishing context for the outreach, referencing [common connection/interest/event] that creates a genuine bridge rather than a forced connection. For new contacts, briefly introduce yourself with relevant credentials or experiences specifically selected to matter to this recipient (not your full bio). Clearly but concisely explain your specific purpose, demonstrating you've done research on their background, company, or recent work (reference something specific that isn't commonly known). If requesting something, use the 5 W's framework (Who, What, When, Where, Why) to be specific, keeping requests reasonable in scope and time commitment. Demonstrate respect for their time by being concise and making the email actionable with a clear, specific next step. If not asking for something, offer genuine value first (useful information, connection, resource) before any requests. Close with gratitude and a relationship-building element that opens the door for ongoing communication without presumption. Include relevant social proof or credibility markers only where they serve the relationship-building purpose rather than appearing as self-promotion.",
  }
];
