
import { SubCategory } from "../types/subcategory-types";

export const IDEA_SUBCATEGORIES: SubCategory[] = [
  {
    id: "business",
    name: "Business Ideas",
    description: "Entrepreneurial concepts",
    defaultPrompt: "Help me brainstorm innovative business ideas related to [challenge]. First, analyze the market landscape: identify 3-5 significant gaps in the current offerings, emerging consumer trends that are gaining momentum but still underserved, and regulatory/technological changes creating new opportunities. For each identified opportunity, develop 2-3 specific business concepts that include: 1) Unique value proposition clearly differentiated from existing solutions, 2) Target customer segments with detailed psychographic and behavioral characteristics, 3) Revenue model options with rough unit economics, 4) Key resources and capabilities required to execute, 5) Potential partnerships that would accelerate growth, 6) Initial go-to-market approach for validation. Consider various business models beyond the obvious (subscription, marketplace, freemium, etc.) and evaluate them against [constraints]. For the most promising 2 ideas, include a brief risk assessment covering market timing, execution challenges, and competitive responses. Focus on ideas that balance innovation with feasibility given the specified constraints, and prioritize concepts with strong product-market fit potential rather than just technical novelty.",
  },
  {
    id: "product",
    name: "Product Concepts",
    description: "New product development ideas",
    defaultPrompt: "Generate product ideas that solve [challenge]. Begin by segmenting the target users into 3-4 distinct personas with different priorities, pain points, and usage contexts. For each persona, develop conceptual solutions that address their specific needs while considering the overall market opportunity. For each product concept, include: 1) Core functionality and key features prioritized by user impact, 2) Unique selling proposition articulated in customer-benefit language, 3) Visual and interaction design direction with references to existing design languages or innovative approaches, 4) Technical feasibility assessment considering [constraints], 5) Potential pricing models aligned with perceived value and cost structure, 6) Key metrics for measuring product success aligned with user outcomes, 7) Competitive positioning against existing alternatives, 8) Future expansion opportunities beyond the MVP. Focus on solutions that balance desirability (what users want), feasibility (what can be built within constraints), and viability (sustainable business model). Include at least one disruptive concept that challenges category conventions and one pragmatic concept that could be implemented with minimal resources. For the most promising concept, outline potential objections from stakeholders and how to address them.",
  },
  {
    id: "solution",
    name: "Problem Solutions",
    description: "Approaches to solve challenges",
    defaultPrompt: "Brainstorm solutions for this problem: [challenge]. Analyze the problem from multiple perspectives: root cause analysis, systems thinking approach, first principles breakdown, and analogous problem comparison from other domains. For each analysis approach, identify key insights that inform potential solution directions. Then develop a diverse solution set including: 1) Quick wins that can be implemented immediately with minimal resources, 2) Structural solutions that address underlying causes rather than symptoms, 3) Behavioral interventions that work with existing human tendencies rather than against them, 4) Technological approaches leveraging emerging capabilities, 5) Policy or process changes that modify the environment in which the problem exists. For each solution type, provide 2-3 specific concepts with implementation considerations within [context] and [constraints]. Evaluate each solution using multiple criteria: effectiveness, resource requirements, time to impact, resistance factors, unintended consequences, and scalability. Finally, propose an integrated approach that combines elements from different solution types into a cohesive strategy with short, medium, and long-term components. Include contingency plans for likely implementation challenges.",
  },
  {
    id: "creative",
    name: "Creative Concepts",
    description: "Artistic and creative ideas",
    defaultPrompt: "Generate creative concepts for [challenge] that are innovative and original. First, establish conceptual foundations by: 1) Identifying unexpected juxtapositions between the subject matter and unrelated domains, 2) Exploring metaphorical representations that create new emotional or intellectual connections, 3) Subverting conventional approaches or expectations within this creative space. For each conceptual direction, develop 3-4 specific creative executions that consider: visual language (color palettes, typography, imagery style), narrative approach (perspective, voice, emotional arc), medium-specific considerations (interaction design for digital, materials for physical, temporal elements for time-based media), and practical production requirements within [context]. Incorporate thoughtful symbolic elements that add depth without being heavy-handed. Balance originality with accessibility for the intended audience, considering cultural references and visual literacy appropriate to [context]. For the most promising concepts, suggest variations that explore different emotional tones (provocative, whimsical, contemplative, etc.) while maintaining conceptual integrity. Include considerations for how these concepts could evolve or expand over time or across different touchpoints rather than being single static executions.",
  },
  {
    id: "marketing",
    name: "Marketing Campaigns",
    description: "Marketing strategy ideas",
    defaultPrompt: "Generate marketing campaign ideas for [product/service] targeting [audience]. Begin with audience analysis: identify 3-4 key psychographic segments within your target market, their primary motivations and objections, media consumption habits, and decision-making factors. Then develop campaign concepts that include: 1) Central campaign theme with emotional core that connects product benefits to audience aspirations, 2) Key message architecture with primary and supporting claims, 3) Creative executions across 4-5 relevant channels (social, video, experiential, etc.) with platform-specific optimizations, 4) Content strategy including hero content, supporting assets, and user-generated components, 5) Journey mapping from awareness to conversion with touchpoint objectives, 6) Measurement framework tied to business outcomes beyond just engagement metrics. Consider [budget/constraints] to ensure feasible execution, focusing on high-impact touchpoints rather than diluted presence across too many channels. Include ideas for generating earned media amplification beyond paid placements. For campaigns with longer timeframes, suggest phased approach with trigger-based optimizations based on early performance indicators. Balance creative differentiation with strategic effectiveness, avoiding concepts that prioritize novelty over persuasiveness for the specific target audience.",
  },
  {
    id: "content-strategy",
    name: "Content Strategy",
    description: "Content planning ideas",
    defaultPrompt: "Develop content strategy ideas for [platform/channel] to reach [target audience]. Begin with a content audit framework to assess current state and gaps. Then create a comprehensive strategic plan including: 1) Audience-centric content pillars (4-6) mapped to specific stages of the customer journey with clear objectives for each stage, 2) Content formats optimized for platform algorithms and audience consumption preferences with specific examples for each, 3) Editorial calendar framework with content cadence recommendations, theme development approach, and seasonality considerations, 4) Content differentiation strategy against competitive landscape with specific whitespace opportunities, 5) Resource optimization model balancing high-production flagship content with scalable regular content, 6) Distribution and amplification tactics for extending organic reach, 7) Performance measurement framework with KPIs tied to business goals beyond vanity metrics, 8) Content repurposing workflow to maximize efficiency across channels. Include specific recommendations for building content authority in key topic areas, leveraging subject matter experts effectively, and implementing governance processes to maintain quality and consistency. Balance aspiration with execution reality given [industry trends] and [technological capabilities], with particular attention to content sustainment beyond initial creation.",
  },
  {
    id: "innovation",
    name: "Product Innovation",
    description: "New product/feature ideas",
    defaultPrompt: "Generate innovative product ideas that solve [problem] for [target market]. First, map the current state of solutions: direct competitors, adjacent solutions users cobble together, and unmet needs driving workarounds. Analyze emerging technology capabilities, shifting user behaviors, and market dynamics creating new possibility spaces. Then develop a spectrum of innovation concepts from incremental improvements to transformative solutions: 1) Feature enhancements that address specific pain points with significant user impact and implementation feasibility, 2) Experience innovations that reimagine user journeys rather than just adding functionality, 3) Business model innovations that change how value is delivered or monetized, 4) Category-creating concepts that define new solution spaces altogether. For each concept, articulate: unique approach, key technical components, experience differentiators, potential barriers to adoption, and competitive moat characteristics. Consider [industry trends] landscape to identify timing advantages, and evaluate ideas against both immediate desirability and future-proofing for emerging use cases. Balance breakthrough thinking with practical considerations for [technological capabilities] and organizational readiness. For the highest potential concepts, outline validation approaches that would de-risk development with minimal investment.",
  }
];
