import { SubCategory } from "../types/subcategory-types";

export const IMAGE_SUBCATEGORIES: SubCategory[] = [
  {
    id: "illustration",
    name: "Illustration",
    description: "Descriptive drawing prompts",
    defaultPrompt: "Create a detailed prompt for an AI illustration of [subject], featuring [details]. \n\n1) Begin with the primary subject description including specific physical attributes, pose, expression, and contextual elements\n\n2) Specify the illustration style in concrete terms (e.g., 'digital painting with visible brushstrokes' rather than just 'digital art')\n\n3) Reference specific artistic influences or comparable artists if relevant\n\n4) Define a [colors] color palette using specific color descriptions rather than just color names ('deep cerulean blue with gold accents' instead of 'blue and yellow')\n\n5) Include detailed lighting specifications:\n   - Light source direction\n   - Quality of light (harsh, diffused, dramatic, etc.)\n   - Specific lighting effects (rim lighting, volumetric beams, etc.)\n   - Shadow characteristics\n\n6) Detail the perspective (eye-level, bird's eye, etc.), composition approach (rule of thirds, centered, etc.), focal point, and depth of field\n\n7) Specify mood and atmosphere through concrete descriptors rather than abstract concepts\n\n8) Add secondary elements that enhance the narrative or composition\n\n9) Include specific technical parameters like aspect ratio and level of detail\n\n10) Exclude any elements that should NOT appear in the final illustration",
  },
  {
    id: "photograph",
    name: "Photography",
    description: "Realistic photo prompts",
    defaultPrompt: "Generate a prompt for a photorealistic image of [subject] with [details]. \n\n1) Begin with the main subject described in precise visual terms including scale, position, and distinguishing features\n\n2) Specify camera settings like [settings: focal length (e.g., 'shot on 85mm lens for portrait compression'), aperture (e.g., 'f/1.8 for shallow depth of field'), shutter speed effects if relevant]\n\n3) Detail lighting conditions with specific light quality (soft, harsh, directional), time of day, practical light sources, lighting ratios, and shadow characteristics\n\n4) Define composition elements including framing, perspective height and angle, foreground/middleground/background elements, and intended focal point\n\n5) Specify photographic style through concrete references to photography genres, notable photographers, or iconic images\n\n6) Include environmental context with atmospheric conditions (clear, hazy, foggy) and weather elements if applicable\n\n7) Detail post-processing style (vibrant colors, desaturated, high contrast, film simulation)\n\n8) For portraits, include specific direction for pose, expression, gaze direction, and styling\n\n9) Add technical specifications like resolution and aspect ratio\n\n10) Use photography-specific terminology throughout to guide the AI toward photographic conventions rather than illustrative interpretations",
  },
  {
    id: "3d",
    name: "3D Rendering",
    description: "Three-dimensional visual prompts",
    defaultPrompt: "Create a detailed prompt for a 3D rendering of [subject]. Begin with comprehensive specifications for the main subject, including precise geometry, proportions, and distinctive features. Detail material properties with specific terminology: subsurface scattering values, reflectivity levels, metallicity, roughness/glossiness, transparency, and texture characteristics (procedural patterns, displacement mapping needs). Specify lighting setup with multiple light sources, their exact positions relative to the subject, light types (area, spot, directional, etc.), color temperatures, intensity values, and desired shadow properties. Detail the environment/background with spatial relationship to the main subject, atmospheric effects, and any environmental reflections or light interactions. Specify camera settings including exact perspective (isometric, one-point perspective, etc.), focal length, depth of field, and composition approach. Define rendering style with specific references to rendering engines, global illumination methods, and whether it should be physically accurate or stylized. Include post-processing effects like ambient occlusion, volumetrics, bloom, or color grading. Provide technical specifications like resolution, aspect ratio, and any animation parameters if applicable. The style should be [style: photorealistic/stylized/abstract/technical] with specific visual references to exemplify the desired outcome.",
  },
  {
    id: "concept",
    name: "Concept Art",
    description: "Visuals for products or media",
    defaultPrompt: "Generate a prompt for concept art of [subject] for [purpose: film/game/product design/etc.]. Begin with the subject's core visual identity, contextualizing it within its intended universe or application. Detail both functional aspects (how it works, practical considerations) and aesthetic direction (design language, historical or cultural influences, symbolic elements). For character concepts, include silhouette distinctiveness, characteristic features, personality expressed through design, costume/clothing details with material properties, color symbolism, and scale reference. For environment concepts, specify architectural style, key structural features, natural elements, lighting conditions, atmosphere, season/time of day, weathering/aging, and scale indicators. For vehicle/prop concepts, detail ergonomics, materials, technological level, functional components, and user interaction points. Include specific composition recommendations: perspective choice, focal points, areas requiring detailed elaboration versus suggested elements. Specify the rendering/execution style with concrete artistic references beyond generic terms, including level of detail, texture approach, line quality for sketches, and color treatment. Include design variations or alternative viewpoints that should be considered. Context should include how this concept fits within larger world-building or product development goals, intended emotional response, and key story/function elements it should communicate.",
  },
  {
    id: "product",
    name: "Product Photography",
    description: "Product showcase images",
    defaultPrompt: "Create a product photography prompt for [product] that highlights [key features]. Begin with precise product positioning including angle (straight-on, three-quarter, etc.), orientation, and any specific components that must be visible or featured. Detail studio setup specifications: backdrop type (seamless white/contextual environment/gradient), surface material (reflective, matte, textured), and any props or supporting elements that enhance the product story without distracting. Specify comprehensive lighting setup including main light position and quality (soft box size, diffusion level), fill light approach, accent/rim lighting for dimension, practical lighting for illuminated products, and shadow requirements (eliminated, soft, or deliberately structured). Include composition guidelines with framing approach, negative space utilization, rule of thirds application, and focal length recommendation to control perspective distortion appropriately for the product category. Detail any specialized techniques required (focus stacking for full depth of field, liquid splash capture timing, smoke/vapor effects, motion blur for dynamic products). Specify post-processing requirements including desired level of retouching (natural with minor imperfection vs. perfect), color accuracy considerations (true-to-life vs. enhanced saturation), background treatment, and any compositional elements to be added in post. Include technical specifications like resolution requirements and aspect ratio optimization for intended usage platforms.",
  },
  {
    id: "character",
    name: "Character Design",
    description: "Character concept art",
    defaultPrompt: "Generate a character design prompt for [character type]. Begin with core character identity elements: archetype, personality traits, background/origin, role in their world, and key emotional associations. Detail physical attributes with specificity: body type and proportions (using concrete references rather than abstract descriptions), distinctive facial features, age indicators, and physical capabilities or limitations that inform the design. Specify costume/clothing elements including: historical or cultural influences, practical vs. decorative aspects, material properties, color symbolism, weathering/aging appropriate to character history, and signature accessories that communicate character traits. Detail characteristic poses that demonstrate personality and physical capabilities, facial expressions that reveal emotional range, and dynamic action poses showing how they move or engage with their world. Specify art style with concrete references beyond generic terms (specific artists, animation studios, game titles, or art movements), including level of stylization vs. realism, proportional system, linework approach for 2D or sculpting style for 3D, and rendering technique. Include worldbuilding context that influences the design, evolution possibilities for character development, and specific story moments the design should support. Provide technical specifications like perspective views needed (front, 3/4, profile, back), turnaround requirements, and expression/pose sheets.",
  },
  {
    id: "environment",
    name: "Environment Design",
    description: "Scene and location visuals",
    defaultPrompt: "Create an environment design prompt for [location/scene]. Begin with essential atmosphere and emotional response the environment should evoke, its function within the larger world, and historical/cultural context that influences its design. Detail architectural or natural elements with specific structural features: construction materials, architectural style references, scale indicators, level of weathering/aging, vegetation types and density, geological features, and water elements if applicable. Specify atmospheric conditions with time of day, season, weather elements, air quality (clear, misty, polluted, etc.), and natural or artificial light sources with their qualities and positions. Detail the spatial composition including foreground elements that frame the scene, middle-ground focal points, background elements providing depth, vertical space utilization, negative space balance, and viewer perspective (ground level, elevated, aerial, etc.). Include environmental storytelling elements: signs of habitation or abandonment, evidence of events that occurred, cultural artifacts, contrasting elements creating visual tension, and transitional areas between different zones. Specify art style with concrete references beyond generic terms, including level of detail approach (hyper-detailed vs. suggestive), rendering technique, color palette strategy (limited vs. expansive, harmonious vs. contrasting), and texturing approach. Provide technical specifications like aspect ratio, camera lens perspective simulation, and focal point guidance.",
  }
];
